#!/usr/bin/env node
// Validate hand-authored Weave rules in plugins/weave/rules/.

import fs from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const RULES_DIR = join(ROOT, 'plugins/weave/rules')

export const EXPECTED_RULES = [
  'weave',
  'suggested-stack',
  'testing',
  'frontend-ux',
  'code-quality',
  'security',
  'performance',
]

function frontmatter(markdown) {
  const match = markdown.match(/^---\n([\s\S]*?)\n---/)
  if (!match) throw new Error('missing YAML frontmatter')
  const fields = {}
  for (const line of match[1].split('\n')) {
    const idx = line.indexOf(':')
    if (idx === -1) continue
    fields[line.slice(0, idx).trim()] = line.slice(idx + 1).trim()
  }
  return fields
}

export function checkRules() {
  const problems = []
  const onDisk = fs
    .readdirSync(RULES_DIR)
    .filter((name) => name.endsWith('.mdc'))
    .map((name) => name.replace(/\.mdc$/, ''))
    .sort()

  const expected = [...EXPECTED_RULES].sort()
  if (onDisk.join() !== expected.join()) {
    problems.push(`rules mismatch: expected ${expected.join(', ')}, got ${onDisk.join(', ')}`)
  }

  for (const name of EXPECTED_RULES) {
    const path = join(RULES_DIR, `${name}.mdc`)
    if (!fs.existsSync(path)) {
      problems.push(`missing ${name}.mdc`)
      continue
    }
    const markdown = fs.readFileSync(path, 'utf8')
    if (markdown.includes('Generated by scripts/build-weave.mjs')) {
      problems.push(`${name}.mdc is generated; Weave rules are hand-authored now`)
      continue
    }
    try {
      const fm = frontmatter(markdown)
      if (!fm.description) problems.push(`${name}.mdc missing description`)
      if (fm.alwaysApply !== 'true') {
        problems.push(`${name}.mdc must set alwaysApply: true`)
      }
    } catch (err) {
      problems.push(`${name}.mdc: ${err.message}`)
    }
  }

  return problems
}

const isMain =
  process.argv[1] &&
  fileURLToPath(import.meta.url) === fs.realpathSync(process.argv[1])

if (isMain) {
  const problems = checkRules()
  if (problems.length) {
    for (const problem of problems) console.error(problem)
    process.exit(1)
  }
  console.error(`ok: ${EXPECTED_RULES.length} Weave rules validated`)
}
