#!/usr/bin/env node
// Generate Weave Cursor rules from canonical core/ and stack/ markdown.
// Fails if an expected heading is missing. --check compares to files on disk.

import fs from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const RULES_DIR = join(ROOT, 'plugins/weave/rules')
const GENERATED_BANNER =
  '<!-- Generated by scripts/build-weave.mjs from canonical markdown. Do not edit. -->'

const RULES = [
  {
    file: 'engineering-principles.mdc',
    description:
      'Lattice engineering principles: simplicity, typing, boundaries, errors, tests, and writing style.',
    alwaysApply: true,
    sources: [
      {
        path: 'core/agents-base.md',
        headings: ['Engineering standards', 'Writing style'],
      },
    ],
  },
  {
    file: 'commit-discipline.mdc',
    description:
      'Lattice commit discipline: Conventional Commits, atomic commits, no PII or AI attribution, agents may commit and push without force or hook bypass.',
    alwaysApply: true,
    sources: [{ path: 'core/agents-base.md', headings: ['Commits'] }],
  },
  {
    file: 'working-agreement.mdc',
    description:
      'Lattice working agreement: engagement posture, planning threshold, git safety, and Definition of Done.',
    alwaysApply: true,
    sources: [
      {
        path: 'core/working-agreement.md',
        headings: [
          'Engagement posture (set per project at kickoff in AGENTS.md)',
          'Workflow',
          'Commit discipline',
          'Data & git safety',
          'Definition of Done',
        ],
      },
    ],
  },
  {
    file: 'security-and-agent-safety.mdc',
    description:
      'Lattice security baseline and agent safety: input validation, authorization, secrets, RLS, and banned shortcuts.',
    alwaysApply: true,
    sources: [
      { path: 'core/security-baseline.md', whole: true },
      {
        path: 'core/agent-safety.md',
        headings: [
          'The shortcuts you must not take',
          'Secrets',
          'Destructive changes',
          'Scope',
          'When you are unsure',
        ],
      },
    ],
  },
  {
    file: 'ticket-workflow.mdc',
    description:
      'Lattice ticket workflow: branch naming, empty dev PR bodies, release PR bodies, and tracker setup. Apply when AGENTS.md declares a Tracker or the work involves branches, tickets, or pull requests.',
    alwaysApply: false,
    sources: [
      {
        path: 'core/ticket-workflow.md',
        headings: [
          'Branches',
          'Merging into dev',
          'Releasing to main',
          'Commits',
          'Environments',
          'Tracker setup',
        ],
      },
    ],
  },
  {
    file: 'lattice-stack.mdc',
    description:
      'Lattice stack baseline: Next.js monorepo layout, Clerk-aware RLS, env vars, migrations, deploys, and tests.',
    alwaysApply: false,
    globs: 'apps/**,supabase/**',
    sources: [
      {
        path: 'stack/stack-baseline.md',
        headings: [
          'Layout',
          'Authorization',
          'Environment variables',
          'Migrations',
          'Deploys',
          'Tests',
        ],
      },
    ],
  },
]

export function extractSection(markdown, heading) {
  const needle = `## ${heading}`
  const lines = markdown.split('\n')
  const start = lines.findIndex((line) => line === needle)
  if (start === -1) {
    throw new Error(`missing heading "## ${heading}"`)
  }
  let end = lines.length
  for (let i = start + 1; i < lines.length; i++) {
    if (lines[i].startsWith('## ')) {
      end = i
      break
    }
  }
  return lines.slice(start, end).join('\n').trim()
}

export function extractBody(markdown) {
  const lines = markdown.split('\n')
  const start = lines.findIndex((line) => line.startsWith('# '))
  const rest = (start === -1 ? lines : lines.slice(start + 1)).join('\n').trim()
  if (!rest) throw new Error('source file has no body after the title')
  return rest
}

function readSource(rel) {
  const path = join(ROOT, rel)
  if (!fs.existsSync(path)) throw new Error(`missing source ${rel}`)
  return fs.readFileSync(path, 'utf8')
}

function renderFrontmatter(rule) {
  const lines = ['---', `description: ${rule.description}`]
  if (rule.globs) lines.push(`globs: ${rule.globs}`)
  lines.push(`alwaysApply: ${rule.alwaysApply ? 'true' : 'false'}`, '---')
  return lines.join('\n')
}

export function renderRule(rule) {
  const parts = [renderFrontmatter(rule), '', GENERATED_BANNER, '']
  for (const source of rule.sources) {
    const markdown = readSource(source.path)
    if (source.whole) {
      parts.push(extractBody(markdown), '')
      continue
    }
    for (const heading of source.headings) {
      try {
        parts.push(extractSection(markdown, heading), '')
      } catch (err) {
        throw new Error(`${source.path}: ${err.message}`)
      }
    }
  }
  return parts.join('\n').replace(/\n{3,}/g, '\n\n').trim() + '\n'
}

export function buildRules() {
  return RULES.map((rule) => ({ file: rule.file, content: renderRule(rule) }))
}

function writeRules(built) {
  fs.mkdirSync(RULES_DIR, { recursive: true })
  const expected = new Set(built.map((item) => item.file))
  for (const name of fs.readdirSync(RULES_DIR)) {
    if (name.endsWith('.mdc') && !expected.has(name)) {
      fs.unlinkSync(join(RULES_DIR, name))
    }
  }
  for (const item of built) {
    fs.writeFileSync(join(RULES_DIR, item.file), item.content)
  }
}

export function checkRules(built = buildRules()) {
  const problems = []
  for (const item of built) {
    const path = join(RULES_DIR, item.file)
    if (!fs.existsSync(path)) {
      problems.push(`missing ${item.file}`)
      continue
    }
    const onDisk = fs.readFileSync(path, 'utf8')
    if (onDisk !== item.content) {
      problems.push(`${item.file} is stale; run npm run build:weave`)
    }
  }
  return problems
}

const isMain =
  process.argv[1] &&
  fileURLToPath(import.meta.url) === fs.realpathSync(process.argv[1])

if (isMain) {
  try {
    const built = buildRules()
    if (process.argv.includes('--check')) {
      const problems = checkRules(built)
      if (problems.length) {
        for (const problem of problems) console.error(problem)
        process.exit(1)
      }
      console.error(`ok: ${built.length} Weave rules match canonical sources`)
    } else {
      writeRules(built)
      console.error(`wrote ${built.length} Weave rules to plugins/weave/rules`)
    }
  } catch (err) {
    console.error(err.message)
    process.exit(1)
  }
}
