// Generated by `supabase gen types`. Run after every schema change and commit
// the result so type errors show up in CI rather than at runtime.
//
//   supabase gen types typescript --local > packages/db/src/database.types.ts
//
// Use --linked to generate from the remote project instead.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
